# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artesanias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artesania',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
