# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artesanias', '0003_auto_20160520_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='artesania',
            name='categoria',
            field=models.CharField(choices=[('TM', 'Talla de Madera'), ('CE', 'Cerámica'), ('TJ', 'Tejido'), ('VI', 'Vidrio'), ('OR', 'Orfebrería')], default='OR', max_length=2),
        ),
    ]
