# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artesanias', '0004_artesania_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='artesania',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
