# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artesanias', '0005_artesania_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artesania',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/%Y/%m/%d/'),
        ),
    ]
